name: Informer
version: '1.0'
main: com.m3z0id.informer.Informer
api-version: '1.18.2'
load: STARTUP
authors: [ M3z0id ]
description: Shows you info about a player, like alts or client.

commands:
  client:
    usage: /<command> <player>
    permission: informer.client
  alts:
    usage: /<command> [player]
    permission: informer.alts
  ips:
    usage: /<command> [player]
    permission: informer.ips
  informer:
    usage: /<command> [reload/info]
    permission: informer.info
  dataremove:
    usage: /<command> [ip/player] <value>
    permission: informer.remove

permissions:
  informer.*:
    default: op
